import { amber, indigo, jade, red, slate } from "@radix-ui/colors";

export const colors = {
  main1: indigo.indigo1,
  main2: indigo.indigo2,
  main3: indigo.indigo3,
  main4: indigo.indigo4,
  main5: indigo.indigo5,
  main6: indigo.indigo6,
  main7: indigo.indigo7,
  main8: indigo.indigo8,
  main9: indigo.indigo9,
  main10: indigo.indigo10,
  main11: indigo.indigo11,
  main12: indigo.indigo12,

  gray1: slate.slate1,
  gray2: slate.slate2,
  gray3: slate.slate3,
  gray4: slate.slate4,
  gray5: slate.slate5,
  gray6: slate.slate6,
  gray7: slate.slate7,
  gray8: slate.slate8,
  gray9: slate.slate9,
  gray10: slate.slate10,
  gray11: slate.slate11,

  error1: red.red1,
  error2: red.red2,
  error3: red.red3,
  error4: red.red4,
  error5: red.red5,
  error6: red.red6,
  error7: red.red7,
  error8: red.red8,
  error9: red.red9,
  error10: red.red10,
  error11: red.red11,

  success1: jade.jade1,
  success2: jade.jade2,
  success3: jade.jade3,
  success4: jade.jade4,
  success5: jade.jade5,
  success6: jade.jade6,
  success7: jade.jade7,
  success8: jade.jade8,
  success9: jade.jade9,
  success10: jade.jade10,
  success11: jade.jade11,

  warning1: amber.amber1,
  warning2: amber.amber2,
  warning3: amber.amber3,
  warning4: amber.amber4,
  warning5: amber.amber5,
  warning6: amber.amber6,
  warning7: amber.amber7,
  warning8: amber.amber8,
  warning9: amber.amber9,
  warning10: amber.amber10,
  warning11: amber.amber11,
};
